name: Continuous Integration

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: [2.12.8]
        java: [adopt@1.8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ubuntu-latest-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - shell: bash
        run: sbt ++${{ matrix.scala }} test scripted
